#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-cal10n
Version  : .0.8.1
Release  : 1
URL      : https://github.com/qos-ch/cal10n/archive/v_0.8.1.tar.gz
Source0  : https://github.com/qos-ch/cal10n/archive/v_0.8.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: jdk-cal10n-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-atinject
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-beanutils
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-digester
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-validator
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-hamcrest
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-jtidy
BuildRequires : jdk-junit4
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-impl
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-maven-source-plugin
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy-java
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
No detailed description available

%package data
Summary: data components for the jdk-cal10n package.
Group: Data

%description data
data components for the jdk-cal10n package.


%prep
%setup -q -n cal10n-v_0.8.1

find . -name \*.jar -delete
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove pom:extensions
python3 /usr/share/java-utils/pom_editor.py pom_add_dep org.apache.maven:maven-artifact maven-cal10n-plugin
python3 /usr/share/java-utils/pom_editor.py pom_disable_module cal10n-site
python3 /usr/share/java-utils/pom_editor.py pom_disable_module maven-cal10n-plugin-smoke
python3 /usr/share/java-utils/mvn_package.py :*-{plugin} @1
python3 /usr/share/java-utils/pom_editor.py pom_xpath_inject "pom:plugin[pom:artifactId='maven-jar-plugin']/pom:executions" "
<execution>
<id>default-jar</id>
<phase>skip</phase>
</execution>" cal10n-api

%build
python3 /usr/share/java-utils/mvn_build.py -- -Dproject.build.sourceEncoding=ISO-8859-1

%install
xmvn-install  -R .xmvn-reactor -n cal10n -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/cal10n/cal10n-api.jar
/usr/share/java/cal10n/maven-cal10n-plugin-sources.jar
/usr/share/java/cal10n/maven-cal10n-plugin.jar
/usr/share/maven-metadata/cal10n-plugin.xml
/usr/share/maven-metadata/cal10n.xml
/usr/share/maven-poms/cal10n/cal10n-api.pom
/usr/share/maven-poms/cal10n/cal10n-parent.pom
/usr/share/maven-poms/cal10n/maven-cal10n-plugin.pom
